config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  resources :blood_sugars
  resources :glycemic_indices
  resources :medications
  resources :answers
  resources :questions
  resources :users
  get '/info' => 'questions#info'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  has_one :answer
  belongs_to :user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:user_id, :qustion_text)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :qustion_text %>
    <%= form.text_area :qustion_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Qustion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.user.first_name %></td>
        <td><%= question.qustion_text %></td>
          <% if question.answer === nil %>
          <td>No Answer</td>
          <% else %>
        <td><%= question.answer %></td>
          <% end %>
        <td><%= link_to 'View', question %></td>
        <% if @current_user.user_type === 'doctor' %>
        <td><%= link_to 'Answer Question', new_answer_path %></td>
        <% end %>
        <% if @current_user.id === question.user.id || @current_user.user_type === 'admin' %>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% if @current_user.user_type === 'admin' %>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @current_user.user_type === 'patient' %>
<%= link_to 'New Question', new_question_path %>
<% end %>

app/views/questions/info.html.erb
<h2>What is Diabetes?</h2>
<p>Diabetes is a disease that occurs when your blood glucose, also called blood sugar, is too high. Blood glucose is your main source of energy and comes from the food you eat. Insulin, a hormone made by the pancreas, helps glucose from food get into your cells to be used for energy. Sometimes your body doesn’t make enough—or any—insulin or doesn’t use insulin well. Glucose then stays in your blood and doesn’t reach your cells.
Over time, having too much glucose in your blood can cause health problems. Although diabetes has no cure, you can take steps to manage your diabetes and stay healthy.

Sometimes people call diabetes “a touch of sugar” or “borderline diabetes.” These terms suggest that someone doesn’t really have diabetes or has a less serious case, but every case of diabetes is serious.</p>

<h2>Different Types</h2>
<h3>Type 1</h3>

<p>Diabetes type 1
Type 1 diabetes is an auto-immune disease where the body's immune system attacks the insulin-producing cells of the pancreas. People with type 1 diabetes cannot produce insulin and require lifelong insulin replacement for survival.
The disease can occur at any age, although it mostly occurs in children and young adults. Type 1 diabetes is sometimes referred to as 'juvenile onset diabetes' or 'insulin dependent diabetes'.</p>

<h3>Type 2</h3>

<p>Type 2 diabetes is associated with hereditary factors and lifestyle risk factors including poor diet, insufficient physical activity and being overweight or obese.
People with type 2 diabetes may be able to manage their condition through lifestyle changes; however, diabetes medications or insulin replacement may also be required to control blood sugar levels.
Type 2 diabetes occurs mostly in people aged over 40 years old; however, the disease is also becoming increasingly prevalent in younger age groups.</p>

<h2>Diabetes Management</h2>
<h3>Type 1</h3>
<p>In type 1 diabetes, the pancreas produces little or no insulin which is vital for converting glucose into energy. People with type 1 diabetes need to do the job of the pancreas and replace the insulin via insulin injections or an insulin pump. The insulin acts to reduce the level of glucose in the blood.</p>

<h3>Type 2</h3>
<p>In type 2 diabetes, your pancreas is still working but not as effectively as it needs to. This means your body is building insulin resistance and is unable to effectively convert glucose into energy leaving too much glucose in the blood. Type 2 diabetes can sometimes initially be managed through lifestyle modification including a healthy diet, regular exercise and monitoring your blood glucose levels.</p>

<h2>Prevention</h2>
<p>Evidence, including large-scale randomised control trials, shows type 2 diabetes can be prevented or delayed in up to 58 per cent of cases by maintaining a healthy weight, being physically active and following a healthy eating plan.

People at risk of type 2 diabetes can delay and even prevent the condition by:</p>
<ul>
  <li>Maintaining a healthy weight</li>
  <li>Regular physical activity</li>
  <li>Making healthy food choices</li>
  <li>Managing blood pressure</li>
  <li>Managing cholesterol levels</li>
  <li>Not smoking.</li>
</ul>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @question.user.first_name %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question.qustion_text %>
</p>

<p>
  <strong>Answer:</strong>
  <% if @question.answer === nil %>
  No Answer
  <% else %>
  <%= @question.answer %>
    <% end %>
  <% if @current_user.user_type === 'doctor' %>
  <%= link_to 'Answer Question', new_answer_path %>
  <% end %>
</p>

<% if @current_user.user_type === 'admin' %>
<%= link_to 'Edit', edit_question_path(@question) %> |
<% end %>
<%= link_to 'Back', questions_path %>