config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  resources :blood_sugars
  resources :glycemic_indices
  resources :medications
  resources :answers
  resources :questions
  resources :users
  get '/info' => 'questions#info'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/glycemic_indices_controller.rb
class GlycemicIndicesController < ApplicationController
  before_action :set_glycemic_index, only: [:show, :edit, :update, :destroy]

  # GET /glycemic_indices
  # GET /glycemic_indices.json
  def index
    @glycemic_indices = GlycemicIndex.all
  end

  # GET /glycemic_indices/1
  # GET /glycemic_indices/1.json
  def show
  end

  # GET /glycemic_indices/new
  def new
    @glycemic_index = GlycemicIndex.new
  end

  # GET /glycemic_indices/1/edit
  def edit
  end

  # POST /glycemic_indices
  # POST /glycemic_indices.json
  def create
    @glycemic_index = GlycemicIndex.new(glycemic_index_params)

    respond_to do |format|
      if @glycemic_index.save
        format.html { redirect_to @glycemic_index, notice: 'Glycemic index was successfully created.' }
        format.json { render :show, status: :created, location: @glycemic_index }
      else
        format.html { render :new }
        format.json { render json: @glycemic_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glycemic_indices/1
  # PATCH/PUT /glycemic_indices/1.json
  def update
    respond_to do |format|
      if @glycemic_index.update(glycemic_index_params)
        format.html { redirect_to @glycemic_index, notice: 'Glycemic index was successfully updated.' }
        format.json { render :show, status: :ok, location: @glycemic_index }
      else
        format.html { render :edit }
        format.json { render json: @glycemic_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glycemic_indices/1
  # DELETE /glycemic_indices/1.json
  def destroy
    @glycemic_index.destroy
    respond_to do |format|
      format.html { redirect_to glycemic_indices_url, notice: 'Glycemic index was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_glycemic_index
      @glycemic_index = GlycemicIndex.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def glycemic_index_params
      params.require(:glycemic_index).permit(:food, :gi)
    end
end

app/helpers/glycemic_indices_helper.rb
module GlycemicIndicesHelper
end

app/views/glycemic_indices/_form.html.erb
<%= form_with(model: glycemic_index, local: true) do |form| %>
  <% if glycemic_index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(glycemic_index.errors.count, "error") %> prohibited this glycemic_index from being saved:</h2>

      <ul>
      <% glycemic_index.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :food %>
    <%= form.text_field :food %>
  </div>

  <div class="field">
    <%= form.label :gi %>
    <%= form.number_field :gi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/glycemic_indices/edit.html.erb
<h1>Editing Glycemic Index</h1>

<%= render 'form', glycemic_index: @glycemic_index %>

<%= link_to 'Show', @glycemic_index %> |
<%= link_to 'Back', glycemic_indices_path %>

app/views/glycemic_indices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Glycemic Index</h1>
<h2>What is GI?</h2>
<p>Carbohydrate is an essential part of our diets, but not all carbohydrate foods are equal. The Glycemic Index (GI) is a relative ranking of carbohydrate in foods according to how they affect blood glucose levels. Carbohydrates with a low GI value (55 or less) are more slowly digested, absorbed and metabolised and cause a lower and slower rise in blood glucose and, therefore usually, insulin levels.</p>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @glycemic_indices.each do |glycemic_index| %>
      <tr>
        <td><%= glycemic_index.food %></td>
        <td><%= glycemic_index.gi %></td>
        <% if @current_user.user_type === 'admin' %>
        <td><%= link_to 'Edit', edit_glycemic_index_path(glycemic_index) %></td>
        <td><%= link_to 'Destroy', glycemic_index, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%= link_to 'New', new_glycemic_index_path %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/glycemic_indices/new.html.erb
<h1>New Glycemic Index</h1>

<%= render 'form', glycemic_index: @glycemic_index %>

<%= link_to 'Back', glycemic_indices_path %>