config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  resources :blood_sugars
  resources :glycemic_indices
  resources :medications
  resources :answers
  resources :questions
  resources :users
  get '/info' => 'questions#info'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :questions
  has_many :notes
  has_many :medications
  has_many :answers, through: :questions
  enum user_type: [:admin, :doctor, :patient]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :check_if_logged_in, except: [ :new, :create ]
  # before_action :check_if_admin, only: [ :index ]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # @user = User.
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def home
    @blood_sugars = BloodSugar.all
    @medications = Medication.all
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_blood_sugar
      @blood_sugar = BloodSugar.find(params[:id])
    end

    def blood_sugar_params
      params.require(:blood_sugar).permit(:user_id, :time, :level)
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :medicare, :ndss, :phone, :email, :location, :specialization, :user_type, :admin, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :medicare %>
    <%= form.number_field :medicare %>
  </div>

  <div class="field">
    <%= form.label :ndss %>
    <%= form.number_field :ndss %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :specialization %>
    <%= form.text_field :specialization %>
  </div>

  <div class="field">
    <%= form.label :user_type %>
    <%= form.number_field :user_type %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<% if @current_user.user_type === 'admin' %>
  Welcome, Lord Admin
<% end %>

<% if @current_user.user_type === 'doctor' %>
  <p>Your Patients</p>
  <div class="patient_list">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Most Recent Level</th>
          <th>Note Last Updated</th>
          <th></th>
        </tr>
        <tr>
          <td>Jude</td>
          <td>5.3</td>
          <td>26/02/20120</td>
          <td><a href="/users/14">Patient Details</a></td>
        </tr>
      </thead>
    </table>
  </div>
<% end %>

<% if @current_user.user_type === 'patient' %>
  <div class="patient_medications">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Dosage</th>
          <th>Instructions</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    <% @medications.each do |medication| %>
      <tr>
        <td><%= medication.name %></td>
        <td><%= medication.dosage %></td>
        <td><%= medication.instructions %></td>
        <% if @current_user.user_type === 'doctor' %>
        <td><%= link_to 'Edit', edit_medication_path(medication) %></td>
        <td><%= link_to 'Delete', medication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  </div>
  <div class="patient_levels">
    <table>
      <thead>
        <tr>
          <th>Day</th>
          <th>Time</th>
          <th>Level</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @blood_sugars.each do |blood_sugar| %>
          <tr>
            <% if blood_sugar.user_id === @current_user.id %>
            <td>Monday</td>
            <td>12:00 PM</td>
            <td><%= blood_sugar.user_id %></td>
            <td><%= blood_sugar.time %></td>
            <td><%= blood_sugar.level %></td>
            <td><%= link_to 'Edit', edit_blood_sugar_path(blood_sugar) %></td>
            <td><%= link_to 'Delete', blood_sugar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>  </div>
  <%= link_to 'History', blood_sugars_path %>
  <div class="doctors_notes">
    <div class="note_header">Ram's Notes</div>
    <div class="latest_note">Increased insulin by 2 units per day</div>

  </div>

<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Medicare</th>
      <th>Ndss</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Location</th>
      <th>Specialization</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.medicare %></td>
        <td><%= user.ndss %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= user.specialization %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>User Profile</h1>
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if @user.user_type === "patient" %>
<p>
  <strong>Medicare:</strong>
  <%= @user.medicare %>
</p>

<p>
  <strong>Ndss:</strong>
  <%= @user.ndss %>
</p>
<% end %>

<% if @user.user_type === "doctor" %>


<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @user.specialization %>
</p>

<% end %>

<% if @user === @current_user %>
<%= link_to 'Edit Profile', edit_user_path(@user) %>
<% end %>